# Generated by Django 5.0.4 on 2024-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_4_app', '0002_delete_projectdetail_remove_project_supvervisor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='research_area',
            new_name='research_areas',
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='location'),
        ),
    ]
