# Generated by Django 5.0.4 on 2024-05-22 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_4_app', '0003_rename_research_area_project_research_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='assignment_4_app.supervisor'),
        ),
    ]
