# Generated by Django 5.0.4 on 2024-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_4_app', '0006_projectapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topic_num',
            field=models.PositiveIntegerField(null=True, verbose_name='Topic number'),
        ),
    ]
