# Generated by Django 5.0.4 on 2024-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topic_num',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Topic number'),
        ),
    ]
