# Generated by Django 5.0.4 on 2024-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_projectchangerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
