# Generated by Django 5.0.6 on 2024-05-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0008_category_remove_project_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("Rejected", "rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
