# Generated by Django 5.0.4 on 2024-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_location_remove_project_location_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='projectchangerequest',
            name='research_areas',
            field=models.CharField(max_length=100, null=True, verbose_name='research_areas'),
        ),
    ]
