# Generated by Django 5.0.4 on 2024-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_research_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('Rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='research_areas',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
