# Generated by Django 5.0.4 on 2024-05-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_projectchangerequest_status_and_more'),
    ]

    operations = [
        migrations.RenameModel('Research_areas', 'ResearchArea'),
    ]
