# Generated by Django 5.0.4 on 2024-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20240527_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='research_areas',
        ),
        migrations.RemoveField(
            model_name='projectchangerequest',
            name='research_areas',
        ),
        migrations.AddField(
            model_name='project',
            name='research_areas',
            field=models.ManyToManyField(blank=True, to='management.researcharea'),
        ),
        migrations.AddField(
            model_name='projectchangerequest',
            name='research_areas',
            field=models.ManyToManyField(blank=True, to='management.researcharea'),
        ),
    ]
