# Generated by Django 5.0.6 on 2024-05-28 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0009_alter_projectchangerequest_status"),
        ("management", "0014_projectchangerequest_status"),
    ]

    operations = []
