# Generated by Django 5.0.4 on 2024-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_merge_20240528_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
